-- MySQL Script generated by MySQL Workbench
-- Seg 17 Out 2016 19:20:37 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaProvasOnline
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaProvasOnline` ;

-- -----------------------------------------------------
-- Schema SistemaProvasOnline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaProvasOnline` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `SistemaProvasOnline` ;

-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Aluno` (
  `cpfAluno` VARCHAR(11) NOT NULL,
  `nomeAluno` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cpfAluno`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Professor` (
  `cpfProfessor` VARCHAR(11) NOT NULL,
  `nomeProfessor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cpfProfessor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ModeloProva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ModeloProva` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ModeloProva` (
  `idModeloProva` INT NOT NULL,
  `dataInicioModeloProva` DATE NOT NULL,
  `dataTerminoModeloProva` DATE NOT NULL,
  `tituloModeloProva` VARCHAR(45) NOT NULL,
  `cpfProfessor` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idModeloProva`, `cpfProfessor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ModeloProva_Professor_idx` ON `ModeloProva` (`cpfProfessor` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ProvaAluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProvaAluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProvaAluno` (
  `idProvaAluno` INT NOT NULL AUTO_INCREMENT,
  `notaProvaAluno` FLOAT NOT NULL,
  `respotasProvaAluno` TINYTEXT NOT NULL,
  `cpfAluno` VARCHAR(11) NOT NULL,
  `idModeloProva` INT NOT NULL,
  `cpfProfessor` VARCHAR(11) NOT NULL,
  `quantidadeMarcada` INT NULL,
  PRIMARY KEY (`idProvaAluno`, `cpfAluno`, `idModeloProva`, `cpfProfessor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ProvaAluno_Aluno1_idx` ON `ProvaAluno` (`cpfAluno` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_ProvaAluno_ModeloProva1_idx` ON `ProvaAluno` (`idModeloProva` ASC, `cpfProfessor` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pergunta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pergunta` (
  `idPergunta` INT NOT NULL,
  `questaoPergunta` MEDIUMTEXT NOT NULL,
  `idModeloProva` INT NOT NULL,
  `cpfProfessor` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idPergunta`, `idModeloProva`, `cpfProfessor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Pergunta_ModeloProva1_idx` ON `Pergunta` (`idModeloProva` ASC, `cpfProfessor` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Alternativa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alternativa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Alternativa` (
  `idAlternativa` INT NOT NULL,
  `alternativa` TINYTEXT NOT NULL,
  `respostaAlternativa` TINYINT(1) NOT NULL,
  `idPergunta` INT NOT NULL,
  `idModeloProva` INT NOT NULL,
  PRIMARY KEY (`idAlternativa`, `idPergunta`, `idModeloProva`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Alternativa_Pergunta1_idx` ON `Alternativa` (`idPergunta` ASC, `idModeloProva` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Aluno_PodeFazer_Prova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno_PodeFazer_Prova` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Aluno_PodeFazer_Prova` (
  `cpfAluno` VARCHAR(11) NOT NULL,
  `idModeloProva` INT NOT NULL,
  PRIMARY KEY (`cpfAluno`, `idModeloProva`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Aluno_has_ModeloProva_ModeloProva1_idx` ON `Aluno_PodeFazer_Prova` (`idModeloProva` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Aluno_has_ModeloProva_Aluno1_idx` ON `Aluno_PodeFazer_Prova` (`cpfAluno` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
